### ISSUE TITLE
Endpoint to Find Delivery Zone Name for an Address

### ISSUE THREAD

**Issue by mattjanssen** [aglipanci/postmates-api#2]
The [Postmates API docs](https://postmates.com/developer/docs/endpoints#get_zones) say "If you need to check to see if an address is within a given zone, use the **[Delivery Quote endpoint](https://postmates.com/developer/docs/endpoints#get_quote)**." But that endpoint doesn't return any zone information.

Do you know if there's an endpoint to submit an `address` and get back a `zone_name`?

**Comment by aglipanci** [comment]
@mattjanssen As far as I know there is no endpoint to enter the address and to get the zone name. Postmates suggests using the Delivery Quote Endpoint to see if you can create a delivery. Using the Delivery Quote Endpoint Postmates can tell you if you can create a delivery and if pickup and dropoff addresses are in the same delivery zone since they do not allow cross zone deliveries.

Hope that was helpful :)
